# Generated by Django 3.2.6 on 2021-08-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_survey', '0002_auto_20210811_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='creator_user_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='user_id',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_survey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
